- name: update the app backup server
  hosts: app_backup
  tasks:
    - name: update apk package versions on the host OS available to be updated
      shell: "/sbin/apk update"

    - name: upgrade the packages on the host OS
      shell: "/sbin/apk upgrade --available"